# Generated by Django 5.0.1 on 2025-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JOB', 'Job'), ('COMPANY', 'Company')], default='JOB', max_length=10)),
                ('description', models.TextField()),
                ('is_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('min_years_of_experience', models.IntegerField(blank=True, null=True)),
                ('max_years_of_experience', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('is_remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lists', models.ManyToManyField(to='job_app.lists')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['rank', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('hq', models.CharField(blank=True, max_length=255, null=True)),
                ('offices', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('latest_funding_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('total_funding_amount', models.IntegerField(default=0)),
                ('latest_funding_amount', models.IntegerField(default=0)),
                ('founders', models.CharField(blank=True, max_length=255, null=True)),
                ('valuation', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('employees', models.IntegerField(default=0)),
                ('investors', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_funding_date', models.DateField(blank=True, null=True)),
                ('industries', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lists', models.ManyToManyField(to='job_app.lists')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['rank', 'name'],
            },
        ),
    ]
