# Generated by Django 4.2.19 on 2025-03-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
