# Generated by Django 4.2.19 on 2025-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_company_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
